### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by zRelux** [kevinrodriguez-io/rn-web-workspace#1]
Nice repo! I pulled it in today to try out seems great! Some advice I may give is to add testing and linting.
Like cypress, detox for the apps react-native-testing-library and react-testing-library and also eslint. It would make for a great repo to use as a template, also an update to the README would be nice.

**Comment by kevinrodriguez-io** [comment]
@zRelux Hi! I can add those later too, the thing is: Eslint and testing are so overdone, so easy to do that I left this as-is, with it's unique workflow, but for the sake of completeness I can make another template based on this one so we can enjoy more things.
