### ISSUE TITLE
NextJS app is broken

### ISSUE THREAD

**Issue by conor909** [kevinrodriguez-io/rn-web-workspace#2]
After running the Next app after initial `yarn` I get `Module not found: Can't resolve '@yourapp/ui'`

**Comment by kevinrodriguez-io** [comment]
Did you run yarn at the bottom level of the project so it bootstraps the workspace?

**Comment by conor909** [comment]
I think I did, but I have since moved on from the project. If its not reproducible it could well have been my error.  Feel free to close.
